/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 computer_and_laptop-blue.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/computer_and_laptop-blue.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[16.678, 8.418, 24.507]} rotation={[-Math.PI, -0.592, -Math.PI]} scale={[2.549, 0.243, 2.549]}>
        <mesh geometry={nodes.Object_4.geometry} material={nodes.Object_4.material} />
        <mesh geometry={nodes.Object_5.geometry} material={nodes.Object_5.material} />
        <mesh geometry={nodes.Object_6.geometry} material={nodes.Object_6.material} />
        <mesh geometry={nodes.Object_7.geometry} material={nodes.Object_7.material} />
        <mesh geometry={nodes.Object_8.geometry} material={nodes.Object_8.material} />
        <mesh geometry={nodes.Object_9.geometry} material={nodes.Object_9.material} />
      </group>
      <group position={[-18.454, 15.918, 9.192]} rotation={[0, 0.926, -Math.PI]} scale={[-5.14, 0.147, 3.341]}>
        <mesh geometry={nodes.Object_31.geometry} material={nodes.Object_31.material} />
        <mesh geometry={nodes.Object_32.geometry} material={nodes.Object_32.material} />
        <mesh geometry={nodes.Object_33.geometry} material={nodes.Object_33.material} />
        <mesh geometry={nodes.Object_34.geometry} material={nodes.Object_34.material} />
        <mesh geometry={nodes.Object_35.geometry} material={nodes.Object_35.material} />
        <mesh geometry={nodes.Object_36.geometry} material={nodes.Object_36.material} />
      </group>
      <group position={[-2.333, 15.958, 2.159]} rotation={[0, 0.005, 0]} scale={[5.607, 0.175, 1.728]}>
        <mesh geometry={nodes.Object_38.geometry} material={nodes.Object_38.material} />
        <mesh geometry={nodes.Object_39.geometry} material={nodes.Object_39.material} />
        <mesh geometry={nodes.Object_40.geometry} material={nodes.Object_40.material} />
      </group>
      <mesh geometry={nodes.Object_11.geometry} material={nodes.Object_11.material} position={[-18.152, 5.799, 9.513]} scale={[2.327, 5.804, 5.98]} />
      <mesh geometry={nodes.Object_13.geometry} material={nodes.Object_13.material} position={[-24.287, 5.799, 15.387]} scale={[2.327, 5.804, 5.98]} />
      <mesh geometry={nodes.Object_15.geometry} material={nodes.Object_15.material} position={[0, 15.452, 0]} scale={[29.541, 0.336, 8.492]} />
      <mesh geometry={nodes.Object_17.geometry} material={nodes.Object_17.material} position={[0, 0, 14.147]} scale={[46.718, 46.718, 26.649]} />
      <mesh geometry={nodes.Object_19.geometry} material={nodes.Object_19.material} position={[0, 21.761, -6.007]} rotation={[Math.PI / 2, 0, 0]} scale={[9.123, 4.323, 5.089]} />
      <mesh geometry={nodes.Object_21.geometry} material={nodes.Object_21.material} position={[0, 21.761, -5.754]} rotation={[Math.PI / 2, 0, 0]} scale={[8.964, 4.204, 4.87]} />
      <mesh geometry={nodes.Object_23.geometry} material={nodes.Object_23.material} position={[-16.887, 21.761, -0.693]} rotation={[Math.PI / 2, 0, -0.57]} scale={[8.964, 4.204, 4.87]} />
      <mesh geometry={nodes.Object_25.geometry} material={nodes.Object_25.material} position={[16.987, 21.761, -0.811]} rotation={[Math.PI / 2, 0, 0.552]} scale={[8.964, 4.204, 4.87]} />
      <mesh geometry={nodes.Object_27.geometry} material={nodes.Object_27.material} position={[0, 4.992, 0.553]} scale={[5.47, 5, 3.905]} />
      <mesh geometry={nodes.Object_29.geometry} material={nodes.Object_29.material} position={[-27.707, 18.537, 8.063]} rotation={[0, 0.588, 0]} scale={[1.076, 1.75, 0.848]} />
      <mesh geometry={nodes.Object_42.geometry} material={nodes.Object_42.material} position={[7.641, 16.001, 4.809]} rotation={[0, 0.415, 0]} scale={[0.751, 0.486, 1.161]} />
      <mesh geometry={nodes.Object_44.geometry} material={nodes.Object_44.material} position={[7.625, 14.269, 3.664]} scale={3.11} />
    </group>
  )
}

useGLTF.preload('/models/computer_and_laptop-blue.glb')
